version: "3"
services:
  runracreview:
    container_name: runracereview
    image: runracereview.azurecr.io/runracereview:0.1
    restart: always
    environment:
      ASPNETCORE_ENVIRONMENT: Production
